import { useMemo, useState, type FormEvent } from 'react'
import { permissions, stores, user as currentUser } from '../api/mockData'
import { Button, Card, DataTable, Field, FloatingButton, SelectField, SidePanel } from '../components/UI'
import type { Store, User } from '../types'
import { initials } from '../utils/format'

const staffNames = [
  ['Peter', 'Troung', 'Pharmacist'], ['Daniel', 'Ngilia', 'Pharmacist'], ['Lee', 'Nguyen', 'Pharmacist'], ['Jojo', 'Kogioumtzis', 'Pharmacy Assistant'], ['Julliene', 'Mezher', 'Pharmacy Assistant'], ['Ange', 'Kogioumtzis', 'Dispensary Tech'], ['Aaron', 'Fisher', 'I.T. Admin'], ['Minh', 'Phan', 'Pharmacist'], ['Cathie', 'Milanovic', 'Dispensary Tech'], ['Jaime', 'Hajnal', 'Pharmacy Assistant'], ['Leona', 'Cini', 'Pharmacy Assistant'], ['Nikoli', 'Fernando', 'Pharmacy Assistant'], ['Belle', 'Gallano', 'Pharmacist'], ['Lany', 'La', 'Management'], ['Adon', 'Borg', 'Pharmacy Assistant'], ['Arya', 'Prasher', 'Pharmacy Assistant'], ['Bahaa', 'Elzoobi', 'Pharmacy Assistant'], ['Shriya', 'Balakrishnan', 'Pharmacy Assistant'], ['Iris', 'Yu', 'Pharmacist'], ['Minh', 'Manikkuwawadu', 'Pharmacist'], ['Prarthana', 'Patel', 'Pharmacist'], ['Sara', 'Nakhla', 'Pharmacist'], ['Chloe', 'Forde', 'Pharmacy Assistant'], ['Dylan', 'Huynh', 'Pharmacist'], ['Joanna', 'Ta', 'Pharmacy Assistant']
]
const employeeRows: User[] = staffNames.map(([first_name, last_name, role], index) => ({ ...currentUser, userID: index < 7 ? index + 1 : 282 + index, username: String(index < 7 ? index + 1 : 282 + index), first_name, last_name, nickname: first_name, role, inactiveDate: [3, 4, 14, 16, 20].includes(index) ? '2026-06-30' : null, permissions: permissions.slice(0, Math.max(3, 10 - index % 7)) }))
const permissionLabels = ['EOD - View', 'EOD - Edit', 'EOD - Export', 'Account Payments - View', 'Account Payments - Edit', 'Account Payments - Export', 'Roster - View', 'Roster - Edit own shifts', 'Roster - Edit all shifts', 'Roster - Edit public holidays', 'Roster - Manage Leave', 'Roster - Export', 'Manage Employees - View', 'Users - Edit', 'Stores - Edit', 'Invoicing - View', 'Invoicing - Edit', 'Invoicing - Export', 'BAS - View', 'BAS - Edit', 'Budget - View', 'Budget - Edit', 'Monthly Summary - View', 'Monthly Summary - Export']

export function EmployeesPage() {
  const [tab, setTab] = useState<'users' | 'stores'>('users')
  const [rows, setRows] = useState(employeeRows)
  const [storeRows, setStoreRows] = useState(stores)
  const [query, setQuery] = useState('')
  const [panel, setPanel] = useState<'user' | 'permissions' | 'store' | null>(null)
  const [form, setForm] = useState<User>(employeeRows.find((row) => row.first_name === 'Aaron')!)
  const [storeForm, setStoreForm] = useState<Store>(stores[0])
  const [selectedPermissions, setSelectedPermissions] = useState(new Set(permissionLabels))
  const [selectedStores, setSelectedStores] = useState(new Set(stores.map((store) => store.storeID)))
  const visibleUsers = useMemo(() => rows.filter((row) => `${row.userID} ${row.nickname} ${row.first_name} ${row.last_name} ${row.role}`.toLowerCase().includes(query.toLowerCase())), [rows, query])
  const editUser = (row?: User) => { const value = row ?? { ...currentUser, userID: 0, username: '', first_name: '', last_name: '', nickname: '', role: '', inactiveDate: null, employments: [], permissions: [] }; setForm(value); setSelectedStores(new Set(value.employments.map((item) => item.storeID))); setPanel('user') }
  const editStore = (store?: Store) => { setStoreForm(store ?? { storeID: 0, storeName: '', storeHours: 0 }); setPanel('store') }
  const saveUser = (event: FormEvent) => { event.preventDefault(); const value = { ...form, employments: stores.filter((store) => selectedStores.has(store.storeID)).map((store, index) => ({ employmentID: index + 1, userID: form.userID, storeID: store.storeID })) }; setRows((current) => value.userID ? current.map((row) => row.userID === value.userID ? value : row) : [...current, { ...value, userID: Date.now() }]); setPanel(null) }
  const saveStore = (event: FormEvent) => { event.preventDefault(); setStoreRows((current) => storeForm.storeID ? current.map((store) => store.storeID === storeForm.storeID ? storeForm : store) : [...current, { ...storeForm, storeID: Date.now() }]); setPanel(null) }
  const removeUser = () => { setRows((current) => current.filter((row) => row.userID !== form.userID)); setPanel(null) }
  const removeStore = () => { setStoreRows((current) => current.filter((store) => store.storeID !== storeForm.storeID)); setPanel(null) }
  return <div className="page management-page"><div className="period-tabs management-tabs"><button className={tab === 'users' ? 'active' : ''} onClick={() => setTab('users')}>USERS</button><button className={tab === 'stores' ? 'active' : ''} onClick={() => setTab('stores')}>STORES</button></div><Card className="desktop-table-card management-card"><header><div><h1>{tab === 'users' ? 'Current Users' : 'Current Stores'}</h1><p>Double click a {tab === 'users' ? 'user' : 'store'} to edit</p></div><label className="management-search"><span>⌕</span><input aria-label={`Search ${tab}`} placeholder="Search..." value={query} onChange={(event) => setQuery(event.target.value)} /></label></header>{tab === 'users' ? <DataTable rows={visibleUsers} onRowClick={editUser} rowClassName={(row: User) => row.inactiveDate ? 'inactive-row' : ''} columns={[{ key: 'userID', label: 'STAFF ID' }, { key: 'nickname', label: 'NICKNAME' }, { key: 'first_name', label: 'FIRST NAME' }, { key: 'last_name', label: 'LAST NAME' }, { key: 'role', label: 'ROLE' }]} /> : <DataTable rows={storeRows.filter((store) => store.storeName.toLowerCase().includes(query.toLowerCase()))} onRowClick={editStore} columns={[{ key: 'storeName', label: 'STORE NAME' }, { key: 'storeHours', label: 'HOURS PER DAY' }]} />}<footer className="table-filter-footer">⚑ &nbsp;&nbsp;⌁</footer></Card><FloatingButton label={tab === 'users' ? 'Add employee' : 'Add store'} onClick={() => tab === 'users' ? editUser() : editStore()} />
    <SidePanel title={`${form.userID ? 'Edit' : 'Add'} user`} open={panel === 'user'} onClose={() => setPanel(null)} onDelete={form.userID ? removeUser : undefined}><form className="form-stack desktop-side-form employee-form" onSubmit={saveUser}><div className="employee-panel-profile"><span className="avatar" style={{ background: form.bgColour, color: form.textColour }}>{initials(form.first_name, form.last_name).slice(0, 1)}</span><span><b>{form.nickname || form.first_name || 'New user'}</b><small>{form.role}</small></span><span className="active-pill">{form.inactiveDate ? 'Inactive' : 'Active'}</span></div><Field label="Username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><Field label="First Name" value={form.first_name} onChange={(event) => setForm({ ...form, first_name: event.target.value })} /><Field label="Last Name" value={form.last_name} onChange={(event) => setForm({ ...form, last_name: event.target.value })} /><Field label="Preferred Name/Nickname (Optional)" value={form.nickname} onChange={(event) => setForm({ ...form, nickname: event.target.value })} /><Field label="Role" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} /><div className="form-grid"><SelectField label="Profile text colour" value={form.textColour} onChange={(event) => setForm({ ...form, textColour: event.target.value })}><option value="#ff003c">🟥 Red</option><option value="#1473e6">🟦 Blue</option></SelectField><SelectField label="Profile background colour" value={form.bgColour} onChange={(event) => setForm({ ...form, bgColour: event.target.value })}><option value="#ffcce6">🌸 #ffcce6</option><option value="#c7e8ff">🟦 #c7e8ff</option></SelectField></div><fieldset className="store-check-list"><legend>Select Stores</legend>{stores.map((store) => <label key={store.storeID}><input type="checkbox" checked={selectedStores.has(store.storeID)} onChange={(event) => setSelectedStores((current) => { const next = new Set(current); event.target.checked ? next.add(store.storeID) : next.delete(store.storeID); return next })} />{store.storeName}</label>)}</fieldset><Button type="button" variant="secondary">Request Password Reset&nbsp; ⟳</Button><Button type="button" variant="secondary" onClick={() => setPanel('permissions')}>Modify Staff Permissions&nbsp; ›</Button><Button type="submit">Save</Button></form></SidePanel>
    <SidePanel title="Edit permissions" open={panel === 'permissions'} onClose={() => setPanel(null)} onBack={() => setPanel('user')}><div className="permissions-panel"><p>Select user permissions:</p>{permissionLabels.map((label) => <label key={label}><input type="checkbox" checked={selectedPermissions.has(label)} onChange={(event) => setSelectedPermissions((current) => { const next = new Set(current); event.target.checked ? next.add(label) : next.delete(label); return next })} />{label}</label>)}</div></SidePanel>
    <SidePanel title={`${storeForm.storeID ? 'Edit' : 'Add'} store`} open={panel === 'store'} onClose={() => setPanel(null)} onDelete={storeForm.storeID ? removeStore : undefined}><form className="form-stack desktop-side-form store-form" onSubmit={saveStore}><Field label="Store Name" value={storeForm.storeName} onChange={(event) => setStoreForm({ ...storeForm, storeName: event.target.value })} /><Field label="Average day length (Hours)" type="number" step="0.5" value={storeForm.storeHours} onChange={(event) => setStoreForm({ ...storeForm, storeHours: Number(event.target.value) })} /><Button type="submit">Save</Button></form></SidePanel>
  </div>
}
