import { useState, type FormEvent } from 'react'
import { credits as initialCredits, invoices as initialInvoices } from '../api/mockData'
import { Button, Card, DataTable, Field, Modal, PageHeader, SelectField, SidePanel, TextArea } from '../components/UI'
import type { Credit, Invoice } from '../types'
import { invoiceVariance } from '../utils/calculations'
import { currentMonth, currency, displayDate, downloadText, toCsv } from '../utils/format'

const emptyInvoice: Invoice = { supplierName: '', storeID: 1, supplierID: 0, invoiceNo: '', invoiceDate: '2026-07-15', dueDate: '2026-08-14', description: 'Pharmacy stock', quantity: 1, unitAmount: 0, importedInvoiceAmount: 0, variance: 0, credits: 0, totalAfterCredits: 0, notes: '', invoiceExists: true, importExists: false, creditExists: false }
const emptyCredit: Credit = { creditID: 0, supplierName: '', supplierID: 0, storeID: 1, creditNo: '', creditDate: '2026-07-15', referenceInvoiceNo: '', creditAmount: 0, notes: '' }

export function InvoicesPage() {
  const [month, setMonth] = useState(currentMonth())
  const [tab, setTab] = useState<'invoices' | 'credits'>('invoices')
  const [invoices, setInvoices] = useState(initialInvoices)
  const [credits, setCredits] = useState(initialCredits)
  const [invoicePanel, setInvoicePanel] = useState(false)
  const [creditPanel, setCreditPanel] = useState(false)
  const [invoice, setInvoice] = useState(emptyInvoice)
  const [credit, setCredit] = useState(emptyCredit)
  const [original, setOriginal] = useState('')
  const [suppliersOpen, setSuppliersOpen] = useState(false)
  const [suppliers, setSuppliers] = useState(['Sigma Healthcare', 'API', 'Symbion'])
  const openInvoice = (row?: Invoice) => { setInvoice(row ?? { ...emptyInvoice, invoiceDate: `${month}-01` as Invoice['invoiceDate'] }); setOriginal(row?.invoiceNo ?? ''); setInvoicePanel(true) }
  const saveInvoice = (event: FormEvent) => { event.preventDefault(); const calculated = { ...invoice, variance: invoiceVariance(invoice.unitAmount * invoice.quantity, invoice.importedInvoiceAmount), totalAfterCredits: invoice.unitAmount * invoice.quantity - invoice.credits }; setInvoices((rows) => original ? rows.map((row) => row.invoiceNo === original ? calculated : row) : [...rows, calculated]); setInvoicePanel(false) }
  const openCredit = (row?: Credit) => { setCredit(row ?? { ...emptyCredit, creditDate: `${month}-01` as Credit['creditDate'] }); setOriginal(row?.creditNo ?? ''); setCreditPanel(true) }
  const saveCredit = (event: FormEvent) => { event.preventDefault(); setCredits((rows) => original ? rows.map((row) => row.creditNo === original ? credit : row) : [...rows, { ...credit, creditID: Date.now() }]); setCreditPanel(false) }
  return <div className="page"><PageHeader title="Invoice Tracking" subtitle="Supplier invoices, imports, credits and variance" month={month} setMonth={setMonth} actions={<><Button variant="ghost" onClick={() => setSuppliersOpen(true)}>Manage suppliers</Button><label className="button button--secondary file-button"><input type="file" accept=".xlsx,.xls,.csv" /><span>Import Invoice Data</span></label><Button variant="secondary" icon="download" onClick={() => downloadText(`invoices-${month}-xero.csv`, toCsv(invoices))}>Export in Xero Format</Button><Button icon="plus" onClick={() => tab === 'invoices' ? openInvoice() : openCredit()}>Add {tab === 'invoices' ? 'invoice' : 'credit'}</Button></>} /><div className="period-tabs compact"><button className={tab === 'invoices' ? 'active' : ''} onClick={() => setTab('invoices')}>INVOICES</button><button className={tab === 'credits' ? 'active' : ''} onClick={() => setTab('credits')}>CREDITS</button></div>
    <Card>{tab === 'invoices' ? <DataTable rows={invoices.filter((row) => row.invoiceDate.startsWith(month))} onRowClick={openInvoice} columns={[{ key: 'supplierName', label: 'Supplier' }, { key: 'invoiceNo', label: 'Invoice no.' }, { key: 'invoiceDate', label: 'Invoice date', render: (r: Invoice) => displayDate(r.invoiceDate) }, { key: 'dueDate', label: 'Due date', render: (r: Invoice) => displayDate(r.dueDate) }, { key: 'unitAmount', label: 'Invoice amount', render: (r: Invoice) => currency.format(r.unitAmount * r.quantity) }, { key: 'importedInvoiceAmount', label: 'Imported amount', render: (r: Invoice) => currency.format(r.importedInvoiceAmount) }, { key: 'variance', label: 'Variance', render: (r: Invoice) => <span className={r.variance === 0 ? 'positive' : 'negative'}>{currency.format(r.variance)}</span> }, { key: 'credits', label: 'Credits', render: (r: Invoice) => currency.format(r.credits) }, { key: 'totalAfterCredits', label: 'Total after credits', render: (r: Invoice) => currency.format(r.totalAfterCredits) }]} /> : <DataTable rows={credits.filter((row) => row.creditDate.startsWith(month))} onRowClick={openCredit} columns={[{ key: 'supplierName', label: 'Supplier' }, { key: 'creditNo', label: 'Credit note no.' }, { key: 'creditDate', label: 'Credit date', render: (r: Credit) => displayDate(r.creditDate) }, { key: 'referenceInvoiceNo', label: 'Reference invoice' }, { key: 'creditAmount', label: 'Amount', render: (r: Credit) => currency.format(r.creditAmount) }, { key: 'notes', label: 'Notes' }]} />}</Card>
    <SidePanel title={`${original ? 'Edit' : 'Add a new'} invoice`} open={invoicePanel} onClose={() => setInvoicePanel(false)}><form className="form-stack" onSubmit={saveInvoice}><SelectField label="Supplier" value={invoice.supplierName} onChange={(e) => setInvoice({ ...invoice, supplierName: e.target.value, supplierID: e.target.selectedIndex })} required><option value="">Select supplier</option>{suppliers.map((s) => <option key={s}>{s}</option>)}</SelectField><Field label="Invoice Number" value={invoice.invoiceNo} onChange={(e) => setInvoice({ ...invoice, invoiceNo: e.target.value })} required /><div className="form-grid"><Field label="Invoice Date" type="date" value={invoice.invoiceDate} onChange={(e) => setInvoice({ ...invoice, invoiceDate: e.target.value as Invoice['invoiceDate'] })} /><Field label="Due Date" type="date" value={invoice.dueDate} onChange={(e) => setInvoice({ ...invoice, dueDate: e.target.value as Invoice['dueDate'] })} /></div><Field label="Description" value={invoice.description} onChange={(e) => setInvoice({ ...invoice, description: e.target.value })} /><div className="form-grid"><Field label="Unit Amount ($)" type="number" step="0.01" value={invoice.unitAmount} onChange={(e) => setInvoice({ ...invoice, unitAmount: Number(e.target.value) })} /><Field label="Expected Unit Amount" type="number" step="0.01" value={invoice.importedInvoiceAmount} onChange={(e) => setInvoice({ ...invoice, importedInvoiceAmount: Number(e.target.value) })} /></div><div className="summary-strip"><span>Variance <b className={invoiceVariance(invoice.unitAmount, invoice.importedInvoiceAmount) === 0 ? 'positive' : 'negative'}>{currency.format(invoiceVariance(invoice.unitAmount, invoice.importedInvoiceAmount))}</b></span></div><TextArea label="Additional Notes" value={invoice.notes} onChange={(e) => setInvoice({ ...invoice, notes: e.target.value.slice(0, 255) })} /><div className="panel-actions">{original && <Button type="button" variant="danger" onClick={() => { setInvoices(invoices.filter((r) => r.invoiceNo !== original)); setInvoicePanel(false) }}>Delete</Button>}<Button type="submit">Save</Button></div></form></SidePanel>
    <SidePanel title={`${original ? 'Edit' : 'Add a new'} credit`} open={creditPanel} onClose={() => setCreditPanel(false)}><form className="form-stack" onSubmit={saveCredit}><SelectField label="Supplier" value={credit.supplierName} onChange={(e) => setCredit({ ...credit, supplierName: e.target.value, supplierID: e.target.selectedIndex })}><option value="">Select supplier</option>{suppliers.map((s) => <option key={s}>{s}</option>)}</SelectField><Field label="Credit Note Number" value={credit.creditNo} onChange={(e) => setCredit({ ...credit, creditNo: e.target.value })} required /><Field label="Reference Invoice Number" value={credit.referenceInvoiceNo} onChange={(e) => setCredit({ ...credit, referenceInvoiceNo: e.target.value })} /><Field label="Credit Date" type="date" value={credit.creditDate} onChange={(e) => setCredit({ ...credit, creditDate: e.target.value as Credit['creditDate'] })} /><Field label="Amount ($)" type="number" step="0.01" value={credit.creditAmount} onChange={(e) => setCredit({ ...credit, creditAmount: Number(e.target.value) })} /><TextArea label="Additional Notes" value={credit.notes} onChange={(e) => setCredit({ ...credit, notes: e.target.value })} /><Button type="submit">Save</Button></form></SidePanel>
    <Modal title="Manage suppliers" open={suppliersOpen} onClose={() => setSuppliersOpen(false)}><div className="manage-list">{suppliers.map((supplier) => <div key={supplier}><span>{supplier}</span><button onClick={() => setSuppliers(suppliers.filter((s) => s !== supplier))}>Remove</button></div>)}</div><form className="inline-form" onSubmit={(e) => { e.preventDefault(); const input = e.currentTarget.elements.namedItem('supplier') as HTMLInputElement; if (input.value.trim()) setSuppliers([...suppliers, input.value.trim()]); input.value = '' }}><Field name="supplier" label="New supplier" /><Button type="submit">Add</Button></form></Modal>
  </div>
}
