import { useMemo, useState, type FormEvent } from 'react'
import { Button, Card, DataTable, Field, FloatingButton, Modal, MonthToolbar, SelectField, SidePanel, TextArea, Toggle } from '../components/UI'
import type { LeaveRequest, Shift } from '../types'
import { displayDate, initials } from '../utils/format'

const dayNames = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']
const shortMonths = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const iso = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}` as Shift['shiftStartDate']
const addDays = (date: Date, amount: number) => { const result = new Date(date); result.setDate(result.getDate() + amount); return result }
const mondayOf = (date: Date) => { const result = new Date(date); const day = result.getDay() || 7; result.setDate(result.getDate() - day + 1); result.setHours(0, 0, 0, 0); return result }
const people = [
  ['Ange', 'Kogioumtzis', 'Dispensary Tech', '#0b477e', '#fff'], ['Alexis', 'Gorevski', 'Pharmacy Assistant', '#edc6eb', '#fff'], ['Belle', 'Gallano', 'Pharmacist', '#c8f2d5', '#208743'], ['Cathie', 'Milanovic', 'Dispensary Tech', '#f35bae', '#fff'], ['Daniel', 'Ngilia', 'Pharmacist', '#0db6c4', '#063c45'], ['Minh', 'Phan', 'Pharmacist', '#ffe0a5', '#fff'], ['Nikoli', 'Fernando', 'Pharmacy Assistant', '#12c2c7', '#fff'], ['Peter', 'Troung', 'Pharmacist', '#2b78c5', '#fff'], ['Chloe', 'Forde', 'Pharmacy Assistant', '#dc42d4', '#fff'], ['Jaime', 'Hajnal', 'Pharmacy Assistant', '#087e62', '#fff'], ['Riley', 'Young', 'Pharmacy Assistant', '#231789', '#fff']
]
const dayShifts = [
  [['Ange', '09:00', '19:00'], ['Belle', '13:00', '19:00'], ['Cathie', '10:00', '17:00'], ['Daniel', '16:00', '19:00'], ['Minh', '09:00', '15:00'], ['Nikoli', '16:00', '19:00']],
  [['Alexis', '16:00', '19:00'], ['Ange', '09:00', '16:00'], ['Belle', '09:00', '15:00'], ['Cathie', '10:00', '19:00'], ['Minh', '13:00', '19:00'], ['Peter', '13:00', '19:00']],
  [['Alexis', '16:00', '19:00'], ['Ange', '09:00', '16:00'], ['Belle', '11:00', '19:00'], ['Cathie', '12:00', '19:00'], ['Minh', '09:00', '13:00'], ['Minh', '13:00', '15:00']],
  [['Ange', '09:00', '16:00'], ['Belle', '09:00', '19:00'], ['Cathie', '12:00', '19:00'], ['Chloe', '16:00', '19:00'], ['Minh', '09:00', '15:00'], ['Nikoli', '16:00', '19:00']],
  [['Ange', '09:00', '16:00'], ['Belle', '09:00', '15:30'], ['Cathie', '09:00', '12:00'], ['Jaime', '10:00', '19:00'], ['Minh', '13:00', '19:00'], ['Riley', '16:00', '19:00']],
  [['Ange', '09:00', '17:00'], ['Belle', '09:00', '17:00'], ['Riley', '12:00', '17:00']], []
]
const initialShifts: Shift[] = dayShifts.flatMap((items, dayIndex) => items.map(([first, start, end], index) => { const person = people.find(([name]) => name === first)!; const date = `2026-07-${String(6 + dayIndex).padStart(2, '0')}` as Shift['shiftStartDate']; return { shiftID: dayIndex * 10 + index + 1, storeID: 1, userID: people.indexOf(person) + 1, shiftStartTime: start, shiftEndTime: end, shiftStartDate: date, shiftEndDate: date, thirtyMinBreaks: 1, tenMinBreaks: 1, repeating: true, daysPerRepeat: 7, first_name: person[0], last_name: person[1], nickname: person[0], role: person[2], profileBG: person[3], profileText: person[4], originalDate: null } }))
const emptyShift: Shift = { ...initialShifts[0], shiftID: 0, shiftStartTime: '09:00', shiftEndTime: '17:00', repeating: false }
const initialLeaves: LeaveRequest[] = Array.from({ length: 22 }, (_, index) => ({ leaveID: index + 1, storeID: 1, userID: index % people.length + 1, employeeFirstName: index % 4 === 0 ? 'Angela' : index % 3 === 0 ? 'Nikoli' : 'Minh', employeeLastName: index % 4 === 0 ? 'Kogioumtzis' : index % 3 === 0 ? 'Fernando' : 'Phan', employeeRole: index % 4 === 0 ? 'Dispensary Tech' : index % 3 === 0 ? 'Pharmacy Assistant' : 'Pharmacist', fromDate: `2026-07-${String(index % 28 + 1).padStart(2, '0')}T09:00`, toDate: `2026-07-${String(index % 28 + 1).padStart(2, '0')}T19:00`, leaveType: index % 3 === 0 ? 'Annual Leave' : 'Sick Leave', leaveReason: index % 3 === 0 ? 'appointment' : 'with certificate' }))

export function RosterPage() {
  const [week, setWeek] = useState(new Date(2026, 6, 6))
  const [shifts, setShifts] = useState(initialShifts)
  const [form, setForm] = useState(emptyShift)
  const [panel, setPanel] = useState(false)
  const [leaveMode, setLeaveMode] = useState(false)
  const [leavePanel, setLeavePanel] = useState(false)
  const [leaves, setLeaves] = useState(initialLeaves)
  const [specialDate, setSpecialDate] = useState<string | null>(null)
  const [publicHoliday, setPublicHoliday] = useState(false)
  const [specialReason, setSpecialReason] = useState('')
  const dates = useMemo(() => dayNames.map((_, index) => iso(addDays(week, index))), [week])
  const open = (shift?: Shift, date = dates[0]) => { setForm(shift ?? { ...emptyShift, shiftStartDate: date, shiftEndDate: date }); setPanel(true) }
  const selectStaff = (id: number) => { const person = people[id - 1]; setForm({ ...form, userID: id, first_name: person[0], last_name: person[1], nickname: person[0], role: person[2], profileBG: person[3], profileText: person[4] }) }
  const save = (event: FormEvent) => { event.preventDefault(); setShifts((current) => form.shiftID ? current.map((shift) => shift.shiftID === form.shiftID ? form : shift) : [...current, { ...form, shiftID: Date.now() }]); setPanel(false) }
  const remove = () => { setShifts((current) => current.filter((shift) => shift.shiftID !== form.shiftID)); setPanel(false) }
  if (leaveMode) return <div className="page desktop-data-page leave-page"><MonthToolbar value="2026-07" onChange={() => undefined} actions={<Button onClick={() => setLeaveMode(false)}>Return to Roster</Button>} /><Card className="desktop-table-card leave-table-card"><header><h1>Leave Requests this month</h1><label className="management-search"><span>⌕</span><input aria-label="Search leave" placeholder="Search..." /></label></header><DataTable rows={leaves} onRowClick={() => setLeavePanel(true)} columns={[{ key: 'employeeFirstName', label: 'Employee name', render: (leave: LeaveRequest) => `${leave.employeeFirstName} ${leave.employeeLastName}` }, { key: 'employeeRole', label: 'Employee Role' }, { key: 'leaveType', label: 'Leave Type' }, { key: 'fromDate', label: 'Leave Start', render: (leave: LeaveRequest) => `${displayDate(leave.fromDate)} ${leave.fromDate.slice(11)}` }, { key: 'toDate', label: 'Leave End', render: (leave: LeaveRequest) => `${displayDate(leave.toDate)} ${leave.toDate.slice(11)}` }, { key: 'leaveReason', label: 'Reason' }]} /></Card><FloatingButton label="Add leave request" onClick={() => setLeavePanel(true)} /><LeavePanel open={leavePanel} onClose={() => setLeavePanel(false)} onSave={(leave) => { setLeaves([...leaves, leave]); setLeavePanel(false) }} /></div>
  return <div className="page roster-page"><Card className="roster-control-card"><div className="roster-toolbar"><div className="week-selector"><b>NOW SHOWING THE WEEK OF:</b><button className="date-trigger"><span>{displayDate(dates[0])}</span><span>▣</span></button><button onClick={() => setWeek(addDays(week, -7))}>‹</button><button onClick={() => setWeek(addDays(week, 7))}>›</button><button onClick={() => setWeek(new Date(2026, 6, 6))}>TODAY</button></div><div className="page-actions"><Button variant="secondary">⇧&nbsp; Export</Button><Button onClick={() => setLeaveMode(true)}>Manage Staff Leave</Button></div></div><div className="roster-day-tabs">{dates.map((date, index) => <button key={date} className={index === 0 ? 'active' : ''} onDoubleClick={() => setSpecialDate(date)}><b>{dayNames[index]}</b><span>{shortMonths[Number(date.slice(5, 7)) - 1]} {Number(date.slice(-2))}</span></button>)}</div></Card><div className="desktop-roster-grid">{dates.map((date) => <section key={date}>{shifts.filter((shift) => shift.shiftStartDate === date).map((shift) => <button className={`desktop-shift-card ${['Belle', 'Minh', 'Nikoli', 'Ange'].includes(shift.first_name) && Number(date.slice(-2)) % 3 === 0 ? 'desktop-shift-card--leave' : ''}`} key={shift.shiftID} onClick={() => open(shift)}><header><span className="avatar" style={{ background: shift.profileBG, color: shift.profileText }}>{initials(shift.first_name).slice(0, 1)}</span><span><b>{shift.nickname}</b><small>{shift.role}</small></span></header><div><span>◷</span><strong>{toClock(shift.shiftStartTime)}</strong><span>-</span><strong>{toClock(shift.shiftEndTime)}</strong></div>{['Belle', 'Minh', 'Nikoli', 'Ange'].includes(shift.first_name) && Number(date.slice(-2)) % 3 === 0 && <em>On Leave</em>}</button>)}</section>)}</div><FloatingButton label="Add shift" onClick={() => open()} />
    <SidePanel title={`${form.shiftID ? 'Edit' : 'Add'} shift`} open={panel} onClose={() => setPanel(false)} onDelete={form.shiftID ? remove : undefined}><form className="form-stack desktop-side-form shift-form" onSubmit={save}><SelectField label="Employee Name" value={form.userID} onChange={(event) => selectStaff(Number(event.target.value))}>{people.map((person, index) => <option key={person[0]} value={index + 1}>{person[0]}</option>)}</SelectField><Field label="Shift Date" type="date" value={form.shiftStartDate} onChange={(event) => setForm({ ...form, shiftStartDate: event.target.value as Shift['shiftStartDate'], shiftEndDate: event.target.value as Shift['shiftEndDate'] })} /><div className="form-grid"><Field label="Start Time" type="time" value={form.shiftStartTime} onChange={(event) => setForm({ ...form, shiftStartTime: event.target.value })} /><Field label="End Time" type="time" value={form.shiftEndTime} onChange={(event) => setForm({ ...form, shiftEndTime: event.target.value })} /></div><h3>Breaks</h3><div className="form-grid"><Field label="10min Breaks (Paid)" type="number" value={form.tenMinBreaks} onChange={(event) => setForm({ ...form, tenMinBreaks: Number(event.target.value) })} /><Field label="30min Breaks (Unpaid)" type="number" value={form.thirtyMinBreaks} onChange={(event) => setForm({ ...form, thirtyMinBreaks: Number(event.target.value) })} /></div><Toggle label="Repeating Shift" checked={form.repeating} onChange={(repeating) => setForm({ ...form, repeating })} />{form.repeating && <div className="repeat-row"><Field label="Repeat every..." type="number" value={form.daysPerRepeat} onChange={(event) => setForm({ ...form, daysPerRepeat: Number(event.target.value) })} /><SelectField label=""><option>Days</option><option>Weeks</option></SelectField></div>}<Button type="submit">Save</Button></form></SidePanel>
    <Modal title={`Editing ${dayNames[dates.indexOf(specialDate as Shift['shiftStartDate'])]?.toLowerCase() ?? 'day'}, ${specialDate ? displayDate(specialDate) : ''}`} open={Boolean(specialDate)} onClose={() => setSpecialDate(null)} width={350}><form className="form-stack day-edit-form" onSubmit={(event) => { event.preventDefault(); setSpecialDate(null) }}><Toggle label="Public Holiday?" checked={publicHoliday} onChange={setPublicHoliday} /><Field label="Reason" placeholder="Whats special about this day?" value={specialReason} onChange={(event) => setSpecialReason(event.target.value)} /><div className="form-grid"><Button type="submit">OK</Button><Button type="button" variant="secondary" onClick={() => setSpecialDate(null)}>Cancel</Button></div></form></Modal>
  </div>
}

function toClock(value: string) { const [hour, minute] = value.split(':').map(Number); const suffix = hour >= 12 ? 'pm' : 'am'; return <>{String(hour % 12 || 12).padStart(2, '0')}:{String(minute).padStart(2, '0')}<sup>{suffix}</sup></> }

function LeavePanel({ open, onClose, onSave }: { open: boolean; onClose: () => void; onSave: (leave: LeaveRequest) => void }) {
  const [reason, setReason] = useState('')
  return <SidePanel title="Add a new Leave Request" open={open} onClose={onClose}><form className="form-stack desktop-side-form leave-form-panel" onSubmit={(event) => { event.preventDefault(); onSave({ leaveID: Date.now(), storeID: 1, userID: 1, employeeFirstName: 'Ange', employeeLastName: 'Kogioumtzis', employeeRole: 'Dispensary Tech', fromDate: '2026-07-15T09:00', toDate: '2026-07-15T17:00', leaveType: 'Annual Leave', leaveReason: reason }) }}><SelectField label="Employee Name"><option>Ange</option><option>Belle</option></SelectField><SelectField label="Leave Type"><option>Annual Leave</option><option>Sick Leave</option></SelectField><div className="form-grid"><Field label="Start Date" type="date" /><Field label="Start Time" type="time" /></div><div className="form-grid"><Field label="End Date" type="date" /><Field label="End Time" type="time" /></div><TextArea label="Reason:" rows={10} value={reason} onChange={(event) => setReason(event.target.value)} /><Button type="submit">Save</Button></form></SidePanel>
}
