name: jDeploy CI with Maven

on:
  push:
    tags: ['*']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      # Step to extract the version from pom.xml
      - name: Extract version from pom.xml
        id: extract_version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$version" >> $GITHUB_ENV
        shell: bash

      - name: Create application.properties
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" > src/main/resources/application.properties
          echo "DB_USERNAME=${{ secrets.DB_USER }}" >> src/main/resources/application.properties
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
          echo "api.base.url=${{ secrets.API_BASE_URL }}" >> src/main/resources/application.properties
          echo "api.token=${{ secrets.API_TOKEN }}" >> src/main/resources/application.properties
          echo "VERSION=${{ env.VERSION }}" >> src/main/resources/application.properties
        shell: bash

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build App Installer Bundles
        uses: shannah/jdeploy@master
        with:
          github_token: ${{ github.token }}
